// Page Components
export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Directory } from "./Directory";
export { default as FacultyProfile } from "./FacultyProfile";
export { default as Academics } from "./Academics";
export { default as CourseDetails } from "./CourseDetails";
export { default as ProgramDetails } from "./ProgramDetails";
export { default as AdmissionsInfo } from "./AdmissionsInfo";
export { default as Contact } from "./Contact";
export { default as NotFound } from "./NotFound";
export { default as UserProfile } from "./UserProfile";
export { default as EditProfile } from "./EditProfile";
export { default as AcademicCalendar } from "./AcademicCalendar";
export { default as AcademicCalendarView } from "./AcademicCalendarView";
export { default as ExamSchedule } from "./ExamSchedule";
export { default as Notices } from "./Notices";
export { default as Events } from "./Events";
export { default as EventRegistration } from "./EventRegistration";
